on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Check git version
        run: git --version
      - name: Check nodejs version
        run: node --version