on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Check GIT version
        id: check
        # run: echo "node_version=$(node --version)" >> $GITHUB_ENV
        run: echo "git_version=$(git --version)" >> $GITHUB_OUTPUT
      - name: Print the git version output from previous step
        # run: echo Node.js version is ${{ env.node_version }}
        run: echo GIT version is ${{steps.check.outputs.git_version}}
  second-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.test}}
      output2: ${{steps.step2.outputs.test}}
    steps:
      - name: Assign Hello1
        id: step1
        run: echo "test=hello1" >> "$GITHUB_OUTPUT"
      - name: Assign Hello2
        id: step2
        run: echo "test=hello2" >> "$GITHUB_OUTPUT"
  third-job:
    runs-on: ubuntu-latest
    needs: second-job
    steps:
      - env:
          output1: ${{needs.second-job.outputs.output1}}
          output2: ${{needs.second-job.outputs.output2}}
        run: echo $output1 $output2